// object
const data = {
  // array
  products: [
    {
      name: "IPad Pro 13",
      category: "IPads",
      image: "/images/ipad-13.png",
      price: 400,
      brand: "Apple",
      raiting: 9.5,
      numReviews: 10,
      countInStock: 20,
      description: "IPad Pro 13",
    },
    {
      name: "IPad Pro 2020",
      category: "IPads",
      image: "/images/ipad-2020.png",
      price: 600,
      brand: "Apple",
      raiting: 8.5,
      numReviews: 67,
      countInStock: 45,
      description: "IPad Pro 2020",
    },
    {
      name: "IPad Hold Hand",
      category: "IPads",
      image: "/images/ipad-hand.png",
      price: 350,
      brand: "Apple",
      raiting: 4.5,
      numReviews: 67,
      countInStock: 45,
      description: "IPad Hold Hand",
    },
    {
      name: "IPad Pro Stand",
      category: "IPads",
      image: "/images/ipad-stand.png",
      price: 450,
      brand: "Apple",
      raiting: 6.5,
      numReviews: 56,
      countInStock: 200,
      description: "IPad Pro Stand",
    },
    {
      name: "IPad Pro Touch",
      category: "IPads",
      image: "/images/ipad-touch.png",
      price: 800,
      brand: "Apple",
      raiting: 7.5,
      numReviews: 100,
      countInStock: 20,
      description: "IPad Pro Touch",
    },
  ],
};
