  export const products = [
    {
      name: "IPad Pro 13",
      slug: "ipad-pro-13",
      category: "IPads",
      image: "/images/ipad-13.png",
      price: 400,
      brand: "Apple",
      raiting: 9.5,
      numReviews: 10,
      countInStock: 20,
      description: "IPad Pro 13",
    },
    {
      name: "IPad Pro 2020",
      slug: "ipad-pro-2020",
      category: "IPads",
      image: "/images/ipad-2020.png",
      price: 600,
      brand: "Apple",
      raiting: 8.5,
      numReviews: 67,
      countInStock: 45,
      description: "IPad Pro 2020",
    },
    {
      name: "IPad Hold Hand",
      slug: "ipad-hold-hand",
      category: "IPads",
      image: "/images/ipad-hand.png",
      price: 350,
      brand: "Apple",
      raiting: 4.5,
      numReviews: 67,
      countInStock: 45,
      description: "IPad Hold Hand",
    },
    {
      name: "IPad Pro SE",
      slug: "iphone-pro-se",
      category: "IPhones",
      image: "/images/iphone-se.png",
      price: 450,
      brand: "Apple",
      raiting: 6.5,
      numReviews: 56,
      countInStock: 200,
      description: "IPad Pro SE",
    },
    {
      name: "IPhone Pro 13",
      slug: "iphone-pro-13",
      category: "IPhones",
      image: "/images/iphone-13.png",
      price: 800,
      brand: "Apple",
      raiting: 7.5,
      numReviews: 100,
      countInStock: 20,
      description: "IPad Pro 13",
    },
    {
      name: "IPhone Pro 17",
      slug: "iphone-pro-17",
      category: "IPhones",
      image: "/images/iphone-17.png",
      price: 800,
      brand: "Apple",
      raiting: 9.5,
      numReviews: 1000,
      countInStock: 23,
      description: "IPad Pro 17",
    },
  ]
